# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

app_scheme = "NYArticles"
xcworkspace = "NYArticles.xcworkspace"
default_platform(:ios)

platform :ios do
  desc "run unit test"
  lane :tests do
 run_tests(workspace: xcworkspace,
            devices: ["iPhone Xʀ"],
            scheme: app_scheme,
            result_bundle: true)
  end

  desc "code coverage report"
  lane :cov do
xcov(
  workspace: xcworkspace,
  scheme: app_scheme,
  output_directory: "fastlane/xcov_output",
  ignore_file_path: "./fastlane/.xcovignore")
  end
end